import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';

import { Header } from '@/layout/Header';
import './globals.css';

const mulish = Mulish({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Кар’єрне консультування',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header className="fixed w-full h-10 border border-b-gray-700 z-10 bg-gradient-to-t" />

        <main className="flex min-h-screen flex-col">{children}</main>
      </body>
    </html>
  );
}
