import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Header } from '@/layout/Header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header className="fixed w-full h-10 border border-b-gray-700 z-10 bg-gradient-to-t" />

        <main className="flex min-h-screen flex-col items-center justify-between pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
